### ISSUE TITLE
Reports "undefined variable" when variable is used before being assigned

### ISSUE THREAD

**Issue by katspaugh** [AsaAyers/coffeelint-undefined-variables#5]
Hi Asa,

First of all, thank you very much for CoffeeLint and this plugin, even if it doesn't cover all the cases.

Just to add to the list of these edge cases, here's one:
- Define a function that calls another function in its body
- After that, define the function that the first one calls
- The call inside the first function is considered an error

Example code:

``` CoffeeScript
fetchData = ->
    getJSON('/data.json')             # CoffeeLint: Undefined variable; context: getJSON

getJSON = (url) ->
    $http.get(url, { type: 'json' })
```

Compiled JavaScript:

``` JavaScript
var fetchData, getJSON;

fetchData = function() {
  return getJSON('/data.json');
};

getJSON = function(url) {
  return $http.get(url, {
    type: 'json'
  });
};
```

**Comment by AsaAyers** [comment]
I did this one intentionally because I think variable hoisting is a
terrible idea. I welcome a pr to turn this into an option.

I've personally found I'd rather transpile ES6 instead of CoffeeScript. So
I done see me getting around to this issue.

**Comment by katspaugh** [comment]
I see, thanks!
